In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Covid.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [ ]:
print(X)

[[ 21.   99.5]
 [ 22.  100.3]
 [ 23.   99.4]
 [ 24.   98.6]
 [ 19.   98.8]
 [ 20.   98.2]
 [ 21.   98.3]
 [ 20.   98.4]
 [ 26.  100.4]]


In [4]:
print(y)

[1 0 1 0 0 1 1 1 0 0 0 0 1 1 1 0]


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [7]:
print(X_train)

[[100.3   10.    10.   100.9   15.    11.   101.1   20.    12.   101.23
   30.    13.   102.5   15.    14.  ]
 [ 98.1    0.     8.    98.7    0.     8.3   98.5    2.     7.9   99.1
   11.    10.    98.3    1.     7.9 ]
 [ 99.     5.     7.9   99.5   10.     8.5  100.6   25.    11.   100.8
   30.    11.5  101.    50.    13.  ]
 [ 99.1   20.    11.   101.    15.    12.   101.5   10.    13.   102.
   20.    15.   102.9   25.    16.  ]
 [ 97.5    0.     8.    99.     5.     9.   100.1   15.    12.    99.
   10.    13.    98.1    5.    10.  ]
 [ 99.7    5.     8.6   99.9   15.     9.9  101.5   60.    13.9  100.1
   61.    14.1  101.9   72.    14.3 ]
 [ 97.8    0.     9.    99.1   10.     9.5  100.2   15.    10.3   99.5
    7.    10.1   97.5    3.     9.2 ]
 [ 97.8    5.     8.5   99.1   10.     9.1  100.5   20.     9.9   99.5
   15.     9.    99.5    4.     9.5 ]
 [ 98.9    1.     8.2   98.3    0.     8.3   98.7    2.     8.1   99.
   10.     9.    98.5    3.     8.  ]
 [ 97.     0.     7.5

In [6]:
print(X_test)

[[ 98.    0.    8.   99.    2.    8.2  98.    1.    8.   99.   10.    9.
   98.5   3.    8. ]
 [100.   18.    9.   99.8  25.   10.  101.2  50.   13.  100.5  55.   14.5
  101.5  61.   15. ]
 [ 97.8   1.    7.8  97.9   0.    8.1  98.1   1.    7.9  99.1   5.    8.2
   98.2   1.    8.1]
 [ 97.5   0.    7.5  98.    1.    7.8  98.3   1.    7.6  99.3   2.    7.9
   98.1   1.    8. ]]


In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
print(X_train)

[[ 1.88499853  0.76705784  1.40379296  1.91846378  0.94810936  1.09059197
   0.84959079 -0.1297855   0.33724058  1.21536769  0.36567612  0.44813664
   1.15841957 -0.45582109  0.59304535]
 [-0.5074996  -0.93751513 -0.72855078 -0.81923588 -1.56159188 -0.88344042
  -1.91157928 -1.13098794 -1.76304251 -1.09772227 -0.82538325 -1.04565216
  -1.1492621  -1.04038555 -1.46434419]
 [ 0.47124963 -0.08522865 -0.83516796  0.17629127  0.11154228 -0.7372158
   0.31859655  0.14832629 -0.17502359  0.74840587  0.36567612 -0.29875776
   0.33424754  1.00559004  0.25576837]
 [ 0.57999955  2.47163081  2.46996483  2.04290468  0.94810936  1.82171508
   1.27438619 -0.68600908  0.84950475  2.05155515 -0.26119723  1.44399583
   1.37819877 -0.03827505  1.26759929]
 [-1.15999909 -0.93751513 -0.72855078 -0.4459132  -0.7250248  -0.37165425
  -0.2123977  -0.40789729  0.33724058 -1.20631805 -0.88807058  0.44813664
  -1.2591517  -0.87336713 -0.75606255]
 [ 1.23249904 -0.08522865 -0.08884766  0.67405484  0.94810936  0.2

In [10]:
print(X_test)

[[-0.61624952 -0.93751513 -0.72855078 -0.4459132  -1.22696505 -0.95655273
  -2.44257352 -1.1866103  -1.7118161  -1.20631805 -0.88807058 -1.54358175
  -1.0393725  -0.95687634 -1.4306165 ]
 [ 1.55874878  2.13071621  0.33762109  0.54961395  2.62124352  0.35946886
   0.95578964  1.53888523  0.84950475  0.42261855  1.9328595   1.19503103
   0.60897155  1.46489068  0.93032232]
 [-0.83374935 -0.76705784 -0.94178515 -1.81476304 -1.56159188 -1.02966504
  -2.33637467 -1.1866103  -1.76304251 -1.09772227 -1.20150726 -1.94192543
  -1.2042069  -1.04038555 -1.3968888 ]
 [-1.15999909 -0.93751513 -1.26163671 -1.69032214 -1.39427847 -1.24900198
  -2.12397698 -1.1866103  -1.91672176 -0.88053073 -1.38956926 -2.09130431
  -1.2591517  -1.04038555 -1.4306165 ]]


In [11]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [13]:
print(classifier.predict(sc.transform([[99.1,20,11,101,15,12,101.5,10,13,102,20,15,102.9,25,16]])))

[1]


In [14]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 [0 0]]


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[3 0]
 [0 1]]


1.0